import React, { useEffect, useState } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';
import { ConsultationRecord } from '../types';
import { DiagnosisCard } from '../components/DiagnosisCard';
import { TreatmentTimeline } from '../components/TreatmentTimeline';
import { 
  ArrowLeft, 
  Trash2, 
  Copy, 
  Check, 
  Download, 
  Share2, 
  Loader2,
  Calendar,
  AlertCircle
} from 'lucide-react';

export const ConsultationResultPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { token } = useAuth();

  const [consultation, setConsultation] = useState<ConsultationRecord | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [copied, setCopied] = useState<boolean>(false);

  useEffect(() => {
    let isMounted = true;
    if (id && token) {
      api.getConsultationById(id, token)
        .then((record) => {
          if (isMounted) {
            setConsultation(record);
            setLoading(false);
          }
        })
        .catch((err) => {
          if (isMounted) {
            setErrorMsg(err.message || 'Failed to load consultation');
            setLoading(false);
          }
        });
    }
    return () => {
      isMounted = false;
    };
  }, [id, token]);

  const handleDelete = async () => {
    if (!id || !token) return;
    if (!window.confirm('Are you sure you want to delete this consultation record?')) return;

    try {
      await api.deleteConsultation(id, token);
      navigate('/history');
    } catch (err: any) {
      alert(err.message || 'Delete failed');
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleExportMarkdown = () => {
    if (!consultation) return;

    const md = `
# Crop Advisory Diagnostic Report: ${consultation.diagnosis_title}

- **Date:** ${new Date(consultation.created_at).toLocaleString()}
- **Crop Variety:** ${consultation.crop_type}
- **Growth Stage:** ${consultation.growth_stage}
- **Soil Type:** ${consultation.soil_type}
- **Diagnostic Confidence:** ${consultation.confidence_score}%
- **Urgency Tier:** ${consultation.urgency_level}
- **Observed Symptoms:** ${consultation.symptoms_description || 'None noted'}

## Agronomic Summary
${consultation.raw_ai_response?.summary || ''}

## Actionable Treatment Protocols
${(consultation.treatments || []).map((t, i) => `
### ${i + 1}. [${t.actionType}] ${t.title}
- **Timing:** ${t.timing}
- **Protocol:** ${t.description}
`).join('\n')}

---
*Generated by AgriCure AI (Google Gemini 2.5 Flash Multimodal Engine)*
    `.trim();

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Advisory_${consultation.crop_type.replace(/\s+/g, '_')}_${consultation.id.slice(0, 8)}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="py-24 text-center space-y-4">
        <Loader2 className="mx-auto h-8 w-8 text-emerald-400 animate-spin" />
        <p className="text-sm font-semibold text-slate-300">Retrieving advisory report...</p>
      </div>
    );
  }

  if (errorMsg || !consultation) {
    return (
      <div className="mx-auto max-w-md py-16 text-center space-y-4">
        <AlertCircle className="mx-auto h-12 w-12 text-rose-400" />
        <h2 className="text-xl font-bold text-white">Record Not Found</h2>
        <p className="text-xs text-slate-400">{errorMsg || 'Could not locate this advisory record.'}</p>
        <Link
          to="/dashboard"
          className="inline-flex items-center gap-2 rounded-xl bg-slate-800 px-4 py-2 text-xs font-semibold text-white hover:bg-slate-700"
        >
          <ArrowLeft className="h-4 w-4" />
          <span>Return to Dashboard</span>
        </Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-5xl space-y-8 pb-12">
      {/* Top Breadcrumb & Action Toolbar */}
      <div className="no-print flex flex-wrap items-center justify-between gap-4">
        <Link
          to="/history"
          className="flex items-center gap-1.5 text-xs font-semibold text-slate-400 hover:text-white transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          <span>Back to Advisory Archive</span>
        </Link>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyLink}
            className="flex items-center gap-1.5 rounded-lg border border-slate-700 bg-slate-900/80 px-3 py-1.5 text-xs font-medium text-slate-200 hover:bg-slate-800 transition-colors"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copied ? 'Link Copied' : 'Share Link'}</span>
          </button>
          <button
            onClick={handleDelete}
            className="flex items-center gap-1.5 rounded-lg border border-rose-500/30 bg-rose-500/10 px-3 py-1.5 text-xs font-medium text-rose-300 hover:bg-rose-500/20 transition-colors"
            title="Delete consultation"
          >
            <Trash2 className="h-3.5 w-3.5" />
            <span>Delete</span>
          </button>
        </div>
      </div>

      {/* Primary Diagnosis Card */}
      <DiagnosisCard
        consultation={consultation}
        onExportMarkdown={handleExportMarkdown}
        onPrint={handlePrint}
      />

      {/* Actionable Treatment Protocols & Timeline */}
      <TreatmentTimeline
        treatments={consultation.treatments || consultation.raw_ai_response?.treatments || []}
      />
    </div>
  );
};
